version: '3'
services:
  swagger-ui:
    environment:
      - API_URL=http://${DOMAIN}/api/v1/swagger/
  backend:
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
      - 'JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root'
  celeryworker:
    environment:
      - RUN=celery worker -A app.worker -l info -Q main-queue -c 1
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
  backend-tests:
    environment:
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
      - SERVER_NAME=${DOMAIN}
